name: sample split config
description: |
    生成二拆配置文件
options:
    - name: meta_info
      desc: 多样拆分信息文件,一个文库一个文件
      type: string
      required: True
    - name: lane_name
      desc: lane名字
      type: string
      required: True
    - name: library_number
      desc: 文库名字
      type: string
      required: True
diagram: |
    [*]                             -->   get_barcode_config
    [*]                             -->   get_primer_config
    [*]                             -->   get_sample_primer_json
    get_barcode_config              -->   [*]
    get_primer_config               -->   [*]
    get_sample_primer_json          -->   [*]
phase_configs:
    - phase_name: get_barcode_config
      phase_desc: 获得barcode的配置信息
      name: datasplit_v3.sample_split.datasplit_get_barcode_config
      option:
          meta_info: "{meta_info}"
          lane_name: "{lane_name}"
          library_number: "{library_number}"
      publish: ""
      log: 生成barcode_config
    - phase_name: get_primer_config
      phase_desc: 获得primer的配置信息
      name: datasplit_v3.sample_split.datasplit_get_primer_config
      option:
          meta_info: "{meta_info}"
          lane_name: "{lane_name}"
          library_number: "{library_number}"
      publish: ""
      log: 生成primer_config
    - phase_name: get_sample_primer_json
      phase_desc: 获得样本和引物的信息
      name: datasplit_v3.sample_split.datasplit_get_sample_primer_json
      option:
          meta_info: "{meta_info}"
          lane_name: "{lane_name}"
          library_number: "{library_number}"
      publish: ""
      log: 生成sample_primer_json
