var:
  python2: bioinfo/datasplit/Miniconda3/envs/datasplit/bin/python
  python3: bioinfo/datasplit/Miniconda3/envs/datasplit/bin/python3
  python3_all: /mnt/clustre/users/sanger-dev/app/bioinfo/datasplit/Miniconda3/envs/datasplit/bin/python3
  python: /mnt/clustre/users/sanger-dev/app/program/Python-2.7.15/bin/python
  perl: /usr/bin/perl
  java: /mnt/clustre/users/sanger-dev/app/program/jdk1.8.0_66/bin/java
  FileTransfer: /mnt/clustre/users/sanger-dev/wpm2/bin/FileTransfer
  seqkit: bioinfo/datasplit/env/bin/seqkit
  seqtk: bioinfo/datasplit/seqtk/seqtk
  cat: /usr/bin/cat
  cp: /usr/bin/cp
  rm: /usr/bin/rm
  ln: /usr/bin/ln
  ls: /usr/bin/ls
  cut: /usr/bin/cut
  touch: /usr/bin/touch
  xargs: /usr/bin/xargs
  sed: /usr/bin/sed
  mkdir: /usr/bin/mkdir
  gzip: /usr/bin/gzip
  gunzip: /usr/bin/gunzip
  md5sum: /usr/bin/md5sum
  aws: bioinfo/datasplit/env/aws-cli/bin/aws
  bcftools: bioinfo/datasplit/bcftools-1.17/bin/bcftools
  bgzip: bioinfo/datasplit/bcftools-1.17/bin/bgzip
  tabix: bioinfo/datasplit/bcftools-1.17/bin/tabix
  bcl2fastq: bioinfo/datasplit/bcl2fastq
  bcl_convert: bioinfo/datasplit/env/bin/bcl-convert
  generate_lib_sheet: '{package_dir}/datasplit_v3/library_split/datasplit_generate_lib_sheet.py'
  rename_library: '{package_dir}/datasplit_v3/library_split/datasplit_rename_library.py'
  file_arrange: '{package_dir}/datasplit_v3/library_split/file_arrange.py'
  generate_empty_fastq: '{package_dir}/datasplit_v3/library_split/generate_empty_fastq.py'
  rename_self_library: '{package_dir}/datasplit_v3/library_split/rename_self_library.py'
  pretreatment_sample_info: '{package_dir}/datasplit_v3/sample_split/pretreatment_sample_info.py'
  get_barcode_config: '{package_dir}/datasplit_v3/sample_split/get_barcode_config.py'
  get_primer_config: '{package_dir}/datasplit_v3/sample_split/get_primer_config.py'
  get_sample_primer_json: '{package_dir}/datasplit_v3/sample_split/get_sample_primer_json.py'
  get_valid: '{package_dir}/datasplit_v3/sample_split/getValid_rawSeq_byBarcode.2.pl'
  fastp: bioinfo/datasplit/env/bin/fastp
  flash: bioinfo/datasplit/env/bin/flash
  split_by_two_barcode: '{package_dir}/datasplit_v3/sample_split/split_byTwoBarcode.pl'
  trim_length: '{package_dir}/datasplit_v3/sample_split/trim_fqSeq.pl'
  get_clean: '{package_dir}/datasplit_v3/sample_split/extract_meta_clean.py'
  get_raw: '{package_dir}/datasplit_v3/sample_split/get_raw_seq_datasplit_v3.py'
  split_by_one_barcode: '{package_dir}/datasplit_v3/sample_split/split_byF-Barcode.pl'
  split_by_two_barcode_official: '{package_dir}/datasplit_v3/sample_split/split_byTwoBarcode_official.pl'
  split_by_one_barcode_official: '{package_dir}/datasplit_v3/sample_split/split_byF-Barcode_official.pl'
  stat_meta_library_info: '{package_dir}/datasplit_v3/sample_split/stat_meta_library_info.py'
  fastq_stat: /mnt/clustre/users/sanger-dev/app/bioinfo/seq/scripts/FastqStat.jar
  merge_valid_stat: "{package_dir}/datasplit_v3/sample_split/merge_valid_stat.py"
  sample_split_file_arrange: "{package_dir}/datasplit_v3/sample_split/sample_split_file_arrange.py"
  generate_empty_fastq_sample_split: "{package_dir}/datasplit_v3/sample_split/generate_empty_fastq_sample_split.py"
  split_sample_qc_info: "{package_dir}/datasplit_v3/sample_qc/split_sample_qc_info.py"
  cut_left_script: "{package_dir}/datasplit_v3/sample_qc/cut_left51.py"
  fastx_clipper: bioinfo/datasplit/fastx_clipper
  cut_tail_script: "{package_dir}/datasplit_v3/sample_qc/cut_tail.py"
  stat_fastx_clipper: "{package_dir}/datasplit_v3/sample_qc/stat_fastx_clipper.py"
  dynamic_trim: "{software_dir}/bioinfo/datasplit/bin/DynamicTrim.pl"
  skera: "bioinfo/datasplit/smrtlink/install/smrtlink-release_11.1.0.166339/smrtcmds/bin/skera"
  rfam_stat_script: '{package_dir}/datasplit/blast_rfam_stat.py'
  rfam_seed: /mnt/clustre/users/sanger-dev/app/database/align/ncbi/db/rfam_v14.6/Rfam.seed
  split_data_release_info: '{package_dir}/datasplit_v3/data_release/split_data_release_info.py'
  meta_sequence_rename: '{package_dir}/datasplit_v3/data_release/meta_sequence_rename.py'
  arrange_result: '{package_dir}/datasplit_v3/data_release/arrange_result.py'
  get_meta_config: '{package_dir}/datasplit_v3/data_release/get_meta_config.py'
  remove_raw_barcode_primer: '{package_dir}/datasplit_v3/data_release/remove_raw_barcode_primer.pl'
  len_distribution: '{package_dir}/datasplit_v3/pacbio_split/len_distribution.py'
env:
  LD_LIBRARY_PATH: "{software_dir}/bioinfo/datasplit/Miniconda3/envs/datasplit/lib/"
