name: get_barcode_config
description: |
  获取barcode的配置文件
cpu: 1
mem: 4G
queue: chaifen
global_var:
  - python3
  - get_barcode_config
options:
  - name: meta_info
    desc: meta_info信息
    type: string
    required: True
  - name: lane_name
    desc: lane名
    type: string
    required: True
  - name: library_number
    desc: 文库名
    type: string
    required: True
cmds:
  - name: run_get_barcode_config
    formatter: >
      {python3} {get_barcode_config} --infile {meta_info} --outfile {output_dir}/{lane_name}--{library_number}.all.barcode.xls